# Generated by Django 3.2.7 on 2021-10-13 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, unique=True)),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('enable_text', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TextSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='not created yet or title not changed', max_length=100)),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.section')),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('text', models.CharField(blank=True, max_length=255)),
                ('align', models.CharField(choices=[('center', 'center'), ('left', 'left'), ('right', 'right'), ('justify', 'justify')], default='left', max_length=100)),
                ('text_choice', models.CharField(choices=[('p', 'p'), ('h1', 'h1'), ('h2', 'h2'), ('h3', 'h3'), ('h4', 'h4'), ('h5', 'h5'), ('h6', 'h6'), ('pre', 'pre')], default='p', max_length=100)),
                ('font', models.CharField(choices=[('', 'default'), ("'Montserrat', sans-serif;", 'Montserrat'), ("'Oswald', sans-serif;", 'Oswald'), ("'Roboto', sans-serif;", 'Roboto'), ("'RocknRoll One', sans-serif;", 'RocknRoll One'), ("'Stick', sans-serif;", 'Stick')], default='default', max_length=100)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.textsection')),
            ],
        ),
    ]
