# Generated by Django 3.2.7 on 2022-02-07 11:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='background_images/')),
                ('opacity', models.FloatField(choices=[(0.1, 0.1), (0.2, 0.2), (0.3, 0.3), (0.4, 0.4), (0.5, 0.5), (0.6, 0.6), (0.7, 0.7), (0.8, 0.8), (0.9, 0.9), (1.0, 1.0)], default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=50)),
                ('head_image', models.ImageField(blank=True, upload_to='carousel_images')),
                ('header', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('image', models.FileField(blank=True, upload_to='gallery_images/')),
                ('image_title', models.CharField(default='some title', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('On', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NavigationBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(choices=[('navbar navbar-expand-sm bg-light navbar-light', 'light'), ('navbar navbar-expand-sm bg-dark navbar-dark', 'dark'), ('navbar navbar-expand-sm bg-primary navbar-dark', 'blue'), ('navbar navbar-expand-sm bg-success navbar-dark', 'green'), ('navbar navbar-expand-sm bg-info navbar-dark', 'turquoise'), ('navbar navbar-expand-sm bg-warning navbar-dark', 'yellow'), ('navbar navbar-expand-sm bg-danger navbar-dark', 'red'), ('navbar navbar-expand-sm bg-secondary navbar-dark', 'grey')], default='light', max_length=100)),
                ('side_text', models.CharField(blank=True, max_length=50)),
                ('logo_image', models.FileField(upload_to='logo_images/')),
                ('title', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('post_slug', models.SlugField(max_length=255, unique=True)),
                ('summary', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('published', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('enable_images', models.BooleanField(default=False)),
                ('link', models.URLField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AlterModelOptions(
            name='text',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='section',
            name='enable_carousel',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='section',
            name='enable_galleries',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='section',
            name='enable_images',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='section',
            name='enable_posts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='section',
            name='enable_side_posts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='text',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='text',
            name='your_summary',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='text',
            name='font',
            field=models.CharField(blank=True, choices=[('', 'default'), ("'Montserrat', sans-serif;", 'Montserrat'), ("'Oswald', sans-serif;", 'Oswald'), ("'Roboto', sans-serif;", 'Roboto'), ("'RocknRoll One', sans-serif;", 'RocknRoll One'), ("'Stick', sans-serif;", 'Stick')], default='default', max_length=100),
        ),
        migrations.AlterField(
            model_name='text',
            name='text',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='SidePostSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('title', models.CharField(default='not named yet', max_length=100)),
                ('style', models.CharField(choices=[('hovereffect', 'hover effect #1'), ('hovereffect2', 'hover effect #2'), ('hovereffect3', 'hover effect #3')], default='hover effect #1', max_length=100)),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.section')),
            ],
        ),
        migrations.CreateModel(
            name='SidePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=25)),
                ('heading2', models.CharField(blank=True, max_length=25)),
                ('description', models.TextField()),
                ('image_title', models.CharField(blank=True, max_length=25)),
                ('image', models.FileField(upload_to='side_post_images/')),
                ('link', models.CharField(blank=True, max_length=100)),
                ('side', models.CharField(choices=[('LEFT', 'left'), ('RIGHT', 'right')], default='LEFT', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('post_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sidepostsection')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='PostSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('title', models.CharField(default='not created yet or title not changed', max_length=100)),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.section')),
            ],
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to="post's_images")),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='post_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.postsection'),
        ),
        migrations.CreateModel(
            name='ImageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('title', models.CharField(default='not created yet or title not changed', max_length=100)),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.section')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images_images/')),
                ('image_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.imagesection')),
            ],
        ),
        migrations.CreateModel(
            name='GallerySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('title', models.CharField(default='not named yet', max_length=100)),
                ('style', models.CharField(choices=[('hovereffect', 'hover effect #1'), ('hovereffect2', 'hover effect #2'), ('hovereffect3', 'hover effect #3')], default='hovereffect', max_length=100)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.section')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='gallery_images/')),
                ('section', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.gallery')),
            ],
        ),
        migrations.AddField(
            model_name='gallery',
            name='gallery_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.gallerysection'),
        ),
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='carousel_images')),
                ('header', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=150)),
                ('carousel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.carousel')),
            ],
        ),
        migrations.AddField(
            model_name='carousel',
            name='section',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.section'),
        ),
    ]
