# Generated by Django 3.2.7 on 2022-02-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220207_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='centered_header',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='carouselimage',
            name='centered_header',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
