# Generated by Django 3.2.7 on 2022-02-23 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220218_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='enable_info_tab',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='InfoTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='info tab', max_length=25)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('order', models.IntegerField(default=0)),
                ('img1', models.ImageField(upload_to='info_tab_images/')),
                ('heading1', models.CharField(max_length=50)),
                ('content1', models.TextField(max_length=255)),
                ('link1', models.URLField()),
                ('img2', models.ImageField(upload_to='info_tab_images/')),
                ('heading2', models.CharField(max_length=50)),
                ('content2', models.TextField(max_length=255)),
                ('link2', models.URLField()),
                ('img3', models.ImageField(upload_to='info_tab_images/')),
                ('heading3', models.CharField(max_length=50)),
                ('content3', models.TextField(max_length=255)),
                ('link3', models.URLField()),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.section')),
            ],
        ),
    ]
