# Generated by Django 3.2.7 on 2022-02-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220223_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='on_site',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='text',
            field=models.TextField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='text',
            name='your_summary',
            field=models.CharField(default='not defined', max_length=50),
        ),
    ]
