# Generated by Django 3.2.7 on 2022-02-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_infotab'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='enable_info',
            field=models.BooleanField(default=True),
        ),
    ]
