# Generated by Django 3.2.7 on 2022-02-23 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_section_enable_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='enable_info',
            new_name='enable_info_tab',
        ),
    ]
