# Generated by Django 3.2.7 on 2022-02-24 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20220224_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidepost',
            name='enable_link',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sidepost',
            name='description',
            field=models.TextField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='sidepostsection',
            name='style',
            field=models.CharField(blank=True, choices=[('hovereffect', 'hover effect #1'), ('hovereffect2', 'hover effect #2'), ('hovereffect3', 'hover effect #3'), ('', 'None')], default='hover effect #1', max_length=100),
        ),
    ]
