# Generated by Django 3.2.7 on 2022-02-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_text_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='your_summary',
            field=models.CharField(default='not defined', max_length=50),
        ),
    ]
