# Generated by Django 3.2.7 on 2022-02-24 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_sidepostsection_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidepostsection',
            name='style',
            field=models.CharField(blank=True, choices=[('hovereffect', 'hover effect #1'), ('hovereffect2', 'hover effect #2'), ('hovereffect3', 'hover effect #3'), ('', 'None')], default='hover effect #1', max_length=100),
        ),
    ]
